#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $Tyson-14_REPO == "TysonBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3RoYW5vc3VzZXIvVGhhbm9zLVVzZXJCb3QvYXJjaGl2ZS9UaGFub3Nib3Quemlw" | base64 -d
    elif [[ $Tyson-14_REPO == "TysonBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3RoYW5vc3VzZXIvVGhhbm9zLVVzZXJCb3QvYXJjaGl2ZS9UaGFub3Nib3Quemlw" | base64 -d
    elif [[ $Tyson-14_REPO =~ $regex ]]
    then
        if [[ $Tyson-14_REPO_BRANCH ]]
        then
            echo "${Tyson-14_REPO}/archive/${Tyson-14_REPO_BRANCH}.zip"
        else
            echo "$Tyson-14_REPO}/archive/TysonBot.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3RoYW5vc3VzZXIvVGhhbm9zLVVzZXJCb3QvYXJjaGl2ZS9UaGFub3Nib3Quemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="TysonBot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    REBELPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $REBELPATH
    echo " START TysonBot  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
